# fly.toml app configuration file generated for bort on 2026-02-08T02:48:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bort'
primary_region = 'ord'

[build]

[processes]
  app = "node src/index.js"

[[vm]]
  count = 1
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
